version: "3"
services:
    ubuntu:
        image: mi_ubuntu
        container_name: ubuntu
        build:
            context: .
        volumes:
            - ../:/practicas
        privileged: true
        entrypoint: /bin/bash
        stdin_open: true
        tty: true